export const books = [
  {
    id: "1",
    uri: require("@/assets/images/books/entendendoAlgortimos.png"),
    title: "Entendendo Algoritmos",
    author: "Aditya Y. Bhargava",
    rating: 4.5,
    ano: 2016,
    categoria: ["Programação", "Algoritmos", "Ciência da Computação"],
    pais: "Brasil",
    idioma: "Português",
    editora: "Novatec",
    exemplares: 3,
  },
  {
    id: "2",
    uri: require("@/assets/images/books/aprendendoSQL.png"),
    title: "Aprendendo SQL",
    author: "Alan Beaulieu",
    rating: 4.0,
    ano: 2009,
    categoria: ["Banco de Dados", "SQL", "Desenvolvimento"],
    pais: "Brasil",
    idioma: "Português",
    editora: "Alta Books",
    exemplares: 5,
  },
  {
    id: "3",
    uri: require("@/assets/images/books/fundamentosPOOemJava.png"),
    title: "Fundamentos de Computação e Orientação a Objetos usando Java",
    author: "Rafael Santos",
    rating: 4.2,
    ano: 2018,
    categoria: ["Programação", "Java", "Orientação a Objetos"],
    pais: "Brasil",
    idioma: "Português",
    editora: "Casa do Código",
    exemplares: 4,
  },
  {
    id: "4",
    uri: require("@/assets/images/books/logicaDeProgramacao.png"),
    title: "Lógica de Programação",
    author: "Carlos Silva",
    rating: 4.3,
    ano: 2015,
    categoria: ["Programação", "Lógica", "Desenvolvimento"],
    pais: "Brasil",
    idioma: "Português",
    editora: "Novatec",
    exemplares: 6,
  },
  {
    id: "5",
    uri: require("@/assets/images/books/programacaoUtilizandoIA.png"),
    title: "Programação Utilizando IA",
    author: "Ana Pereira",
    rating: 4.7,
    ano: 2021,
    categoria: ["Inteligência Artificial", "Programação", "Tecnologia"],
    pais: "Brasil",
    idioma: "Português",
    editora: "Alta Books",
    exemplares: 2,
  },
  {
    id: "6",
    uri: require("@/assets/images/books/programandoEmCPlusPlus.png"),
    title: "Programando em C++",
    author: "Marcos Lima",
    rating: 4.1,
    ano: 2014,
    categoria: ["Programação", "C++", "Desenvolvimento"],
    pais: "Brasil",
    editora: "Casa do Código",
    exemplares: 7,
    idioma: "Português",
  },
  {
    id: "7",
    uri: require("@/assets/images/books/programandoJava.png"),
    title: "Programando em Java",
    author: "Juliana Costa",
    rating: 4.6,
    ano: 2019,
    categoria: ["Programação", "Java", "Desenvolvimento"],
    pais: "Brasil",
    idioma: "Português",
    editora: "Novatec",
    exemplares: 4,
  },
  {
    id: "8",
    uri: require("@/assets/images/books/pythonFluente.png"),
    title: "Python Fluente",
    author: "Luciana Rocha",
    rating: 4.8,
    ano: 2020,
    categoria: ["Programação", "Python", "Desenvolvimento"],
    pais: "Brasil",
    idioma: "Português",
    editora: "Alta Books",
    exemplares: 3,
  },
  {
    id: "9",
    uri: require("@/assets/images/books/scratch.png"),
    title: "Scratch: Programação para Crianças",
    author: "Fernanda Gomes",
    rating: 4.4,
    ano: 2017,
    categoria: ["Programação", "Educação", "Crianças"],
    pais: "Brasil",
    idioma: "Português",
    editora: "Casa do Código",
    exemplares: 5,
  },
];
